language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install coveralls

script:
  - coverage run --source=transaction setup.py test

# API Key inside Travis CI
deploy:
  provider: heroku
  app: py-chain

after_success:
  - coveralls